name: 'local-cache'
description: "A Github Action to save and restore files across job runs directly in the runner's file system"
inputs:
  key:
    description: 'An explicit key for versioning the cache'
    required: false
  path:
    description: 'The file or folder to be cached'
    required: true
  delete:
    description: 'Deletes specified cache (true/false)'
    required: false
outputs:
  cache-hit:
    description: 'A boolean value to indicate if cache was found and restored'
runs:
  using: 'node16'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
  post-if: success()
